version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    assignees:
      - "Emmy123222"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    assignees:
      - "Emmy123222"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "cargo"
    directory: "/contracts/marketpay-contract"
    schedule:
      interval: "weekly"
    assignees:
      - "Emmy123222"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "cargo"
    directory: "/contracts/arbitrator-registry"
    schedule:
      interval: "weekly"
    assignees:
      - "Emmy123222"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
