/**
 * src/tests/contract/knownSpecGaps.js  (issue #1496)
 *
 * Baseline of documented routes whose live response CANNOT YET be validated
 * against `docs/openapi.yaml`, keyed by `"<METHOD> <path>"` with the reason.
 *
 * These entries exist because the spec itself is incomplete upstream:
 *   - "spec has no <status> response for this route"  → operation never
 *     documents the status the server actually returns (404/400/403/500...)
 *   - "spec entry is description-only"                → the documented response
 *     has no `content.application/json.schema`, so there is nothing to
 *     validate the body against
 *   - "schema mismatch: ..."                          → documented schema and
 *     actual response disagree (known drift to resolve)
 *
 * Contract with openapi.contract.test.js:
 *   - Every entry here IS probed; it must keep failing `toSatisfyApiSpec()`.
 *     If it starts passing, the gap is closed and the test fails asking you
 *     to REMOVE the entry (routes leave the baseline one by one).
 *   - Any route NOT listed here must satisfy the spec exactly, or CI fails.
 *   - When you add a route to openapi.yaml, either document its reachable
 *     statuses with real response schemas, or add it here with a reason.
 *
 * Generated from the initial contract run; shrink it over time.
 */
"use strict";

const KNOWN_SPEC_GAPS = new Map([
  ["DELETE /api/developer/keys/{id}", "spec has no 500 response for this route"],
  ["DELETE /api/profiles/{publicKey}/data", "spec has no 404 response for this route"],
  ["DELETE /api/proposal-templates/{id}", "spec has no 404 response for this route"],
  ["DELETE /api/saved-searches/{id}", "spec entry is description-only (no response schema)"],
  ["DELETE /api/webauthn/admin/credentials/{id}", "spec has no 403 response for this route"],
  ["DELETE /api/webauthn/credentials/{id}", "spec has no 404 response for this route"],
  ["GET /api/admin/2fa/status", "spec has no 403 response for this route"],
  ["GET /api/assessments/results/{publicKey}", "spec entry is description-only (no response schema)"],
  ["GET /api/assessments/{skill}", "spec entry is description-only (no response schema)"],
  ["GET /api/audit", "spec has no 403 response for this route"],
  ["GET /api/audit/{jobId}", "spec has no 404 response for this route"],
  ["GET /api/auth", "schema mismatch: error must be object"],
  ["GET /api/auth/csrf-token", "spec has no 500 response for this route"],
  ["GET /api/auto-convert/history", "spec entry is description-only (no response schema)"],
  ["GET /api/auto-convert/pending", "spec entry is description-only (no response schema)"],
  ["GET /api/auto-convert/settings", "spec has no 404 response for this route"],
  ["GET /api/certificates/user/{publicKey}", "spec entry is description-only (no response schema)"],
  ["GET /api/certificates/{id}", "spec entry is description-only (no response schema)"],
  ["GET /api/contributors", "spec entry is description-only (no response schema)"],
  ["GET /api/dao/arbitrators", "spec entry is description-only (no response schema)"],
  ["GET /api/dao/arbitrators/{publicKey}", "spec entry is description-only (no response schema)"],
  ["GET /api/dao/proposals", "spec entry is description-only (no response schema)"],
  ["GET /api/dao/proposals/{id}", "spec has no 500 response for this route"],
  ["GET /api/dao/treasury", "spec entry is description-only (no response schema)"],
  ["GET /api/developer/keys", "spec has no 500 response for this route"],
  ["GET /api/events/{jobId}", "spec entry is description-only (no response schema)"],
  ["GET /api/faucet/check/{publicKey}", "spec has no 500 response for this route"],
  ["GET /api/health", "spec entry is description-only (no response schema)"],
  ["GET /api/health/db", "spec has no 500 response for this route"],
  ["GET /api/insights/categories", "spec entry is description-only (no response schema)"],
  ["GET /api/insights/competitive", "spec entry is description-only (no response schema)"],
  ["GET /api/insights/skills", "spec entry is description-only (no response schema)"],
  ["GET /api/insights/trends/pay", "spec entry is description-only (no response schema)"],
  ["GET /api/invitations", "spec entry is description-only (no response schema)"],
  ["GET /api/messages/job/{jobId}", "spec has no 404 response for this route"],
  ["GET /api/messages/unread-count", "spec has no 500 response for this route"],
  ["GET /api/nft/freelancer/{publicKey}", "spec has no 400 response for this route"],
  ["GET /api/nft/job/{jobId}", "spec entry is description-only (no response schema)"],
  ["GET /api/notifications", "spec entry is description-only (no response schema)"],
  ["GET /api/notifications/failed-webhooks", "spec entry is description-only (no response schema)"],
  ["GET /api/notifications/preferences", "spec entry is description-only (no response schema)"],
  ["GET /api/notifications/unsubscribe", "spec entry is description-only (no response schema)"],
  ["GET /api/notifications/vapid-public-key", "spec entry is description-only (no response schema)"],
  ["GET /api/onboarding/{publicKey}", "spec entry is description-only (no response schema)"],
  ["GET /api/profiles/{publicKey}", "spec has no 404 response for this route"],
  ["GET /api/profiles/{publicKey}/client-reputation", "spec has no 500 response for this route"],
  ["GET /api/profiles/{publicKey}/earnings", "spec entry is description-only (no response schema)"],
  ["GET /api/profiles/{publicKey}/encryption-key", "spec entry is description-only (no response schema)"],
  ["GET /api/profiles/{publicKey}/endorsements", "spec entry is description-only (no response schema)"],
  ["GET /api/profiles/{publicKey}/price-alerts", "spec has no 500 response for this route"],
  ["GET /api/profiles/{publicKey}/response-time", "spec entry is description-only (no response schema)"],
  ["GET /api/profiles/{publicKey}/spending", "spec has no 500 response for this route"],
  ["GET /api/profiles/{publicKey}/stats", "spec entry is description-only (no response schema)"],
  ["GET /api/proposal-templates", "spec entry is description-only (no response schema)"],
  ["GET /api/public/freelancers/{publicKey}", "spec has no 401 response for this route"],
  ["GET /api/public/jobs", "spec entry is description-only (no response schema)"],
  ["GET /api/public/jobs/{id}", "spec has no 401 response for this route"],
  ["GET /api/rate-limit", "spec has no 404 response for this route (route file not mounted)"],
  ["GET /api/referrals/my-stats", "spec has no 500 response for this route"],
  ["GET /api/referrals/{publicKey}", "spec has no 500 response for this route"],
  ["GET /api/reputation/{userId}", "spec entry is description-only (no response schema)"],
  ["GET /api/saved-searches", "spec entry is description-only (no response schema)"],
  ["GET /api/stats", "spec entry is description-only (no response schema)"],
  ["GET /api/stats/categories", "spec entry is description-only (no response schema)"],
  ["GET /api/stats/trends/escrow", "spec entry is description-only (no response schema)"],
  ["GET /api/stats/trends/jobs", "spec entry is description-only (no response schema)"],
  ["GET /api/stats/xlm-price-history", "spec entry is description-only (no response schema)"],
  ["GET /api/time-entries/job/{jobId}", "spec entry is description-only (no response schema)"],
  ["GET /api/time-entries/job/{jobId}/invoices", "spec entry is description-only (no response schema)"],
  ["GET /api/tokens", "spec entry is description-only (no response schema)"],
  ["GET /api/tokens/popular", "spec entry is description-only (no response schema)"],
  ["GET /api/tokens/search", "spec entry is description-only (no response schema)"],
  ["GET /api/tokens/{contractId}/balance/{publicKey}", "spec has no 500 response for this route"],
  ["GET /api/tokens/{contractId}/metadata", "spec has no 500 response for this route"],
  ["GET /api/transactions/export", "spec entry is description-only (no response schema)"],
  ["GET /api/turrets/config", "spec entry is description-only (no response schema)"],
  ["GET /api/turrets/status", "spec entry is description-only (no response schema)"],
  ["GET /api/verification/{publicKey}", "spec entry is description-only (no response schema)"],
  ["GET /api/webauthn/admin/credentials", "spec has no 403 response for this route"],
  ["GET /api/webauthn/credentials", "spec entry is description-only (no response schema)"],
  ["PATCH /api/auto-convert/settings", "spec has no 404 response for this route"],
  ["PATCH /api/invitations/{id}/decline", "spec has no 404 response for this route"],
  ["PATCH /api/messages/{messageId}/tx-hash", "spec has no 400 response for this route"],
  ["PATCH /api/notifications/preferences", "spec has no 400 response for this route"],
  ["PATCH /api/notifications/read-all", "spec entry is description-only (no response schema)"],
  ["PATCH /api/notifications/{id}/read", "spec has no 404 response for this route"],
  ["PATCH /api/onboarding", "spec entry is description-only (no response schema)"],
  ["PATCH /api/proposal-templates/{id}", "spec has no 400 response for this route"],
  ["PATCH /api/saved-searches/{id}", "spec has no 404 response for this route"],
  ["PATCH /api/time-entries/invoice/{invoiceId}/review", "spec has no 400 response for this route"],
  ["POST /api/admin/2fa/setup", "spec has no 403 response for this route"],
  ["POST /api/admin/2fa/verify", "spec has no 403 response for this route"],
  ["POST /api/ai/score-job", "spec entry is description-only (no response schema)"],
  ["POST /api/applications", "schema mismatch: error must be object"],
  ["POST /api/assessments/{skill}/submit", "spec has no 400 response for this route"],
  ["POST /api/auth", "schema mismatch: error must be object"],
  ["POST /api/auto-convert/{id}/complete", "spec entry is description-only (no response schema)"],
  ["POST /api/auto-convert/{id}/dismiss", "spec has no 404 response for this route"],
  ["POST /api/contributors/refresh", "spec entry is description-only (no response schema)"],
  ["POST /api/dao/arbitrators", "spec has no 500 response for this route"],
  ["POST /api/dao/arbitrators/{publicKey}/vote", "spec has no 500 response for this route"],
  ["POST /api/dao/proposals", "spec has no 500 response for this route"],
  ["POST /api/dao/proposals/{id}/execute", "spec has no 403 response for this route"],
  ["POST /api/dao/proposals/{id}/vote", "spec has no 500 response for this route"],
  ["POST /api/developer/keys", "spec has no 500 response for this route"],
  ["POST /api/developer/keys/{id}/rotate", "spec has no 500 response for this route"],
  ["POST /api/faucet/fund", "spec entry is description-only (no response schema)"],
  ["POST /api/invitations/{id}/accept", "spec has no 404 response for this route"],
  ["POST /api/jobs", "schema mismatch: error must be object"],
  ["POST /api/messages/job/{jobId}", "spec has no 400 response for this route"],
  ["POST /api/messages/job/{jobId}/attachments", "spec has no 400 response for this route"],
  ["POST /api/nft/mint-completion-certificate", "spec entry is description-only (no response schema)"],
  ["POST /api/notifications/failed-webhooks/{id}/retry", "spec has no 403 response for this route"],
  ["POST /api/notifications/push-subscribe", "spec has no 400 response for this route"],
  ["POST /api/notifications/push-unsubscribe", "spec has no 400 response for this route"],
  ["POST /api/profiles", "spec has no 400 response for this route"],
  ["POST /api/profiles/migrate", "spec entry is description-only (no response schema)"],
  ["POST /api/profiles/{publicKey}/availability", "spec has no 400 response for this route"],
  ["POST /api/profiles/{publicKey}/endorse", "spec has no 400 response for this route"],
  ["POST /api/profiles/{publicKey}/price-alerts", "spec has no 500 response for this route"],
  ["POST /api/progress", "spec has no 400 response for this route"],
  ["POST /api/proposal-templates", "spec has no 400 response for this route"],
  ["POST /api/ratings", "spec entry is description-only (no response schema)"],
  ["POST /api/referrals/register", "spec has no 400 response for this route"],
  ["POST /api/saved-searches", "spec entry is description-only (no response schema)"],
  ["POST /api/scope/{sessionId}/renew", "spec entry is description-only (no response schema)"],
  ["POST /api/time-entries", "spec has no 400 response for this route"],
  ["POST /api/time-entries/invoice", "spec has no 400 response for this route"],
  ["POST /api/tokens/validate", "spec entry is description-only (no response schema)"],
  ["POST /api/turrets/estimate", "spec has no 400 response for this route"],
  ["POST /api/turrets/submit", "spec has no 400 response for this route"],
  ["POST /api/verification/email", "spec has no 400 response for this route"],
  ["POST /api/verification/email/confirm", "spec entry is description-only (no response schema)"],
  ["POST /api/verification/id/submit", "spec has no 400 response for this route"],
  ["POST /api/verification/phone", "spec has no 400 response for this route"],
  ["POST /api/verification/phone/confirm", "spec entry is description-only (no response schema)"],
  ["POST /api/webauthn/login-options", "spec has no 400 response for this route"],
  ["POST /api/webauthn/login-verify", "spec has no 400 response for this route"],
  ["POST /api/webauthn/register-options", "spec entry is description-only (no response schema)"],
  ["POST /api/webauthn/register-verify", "spec has no 500 response for this route"],
  ["PUT /api/profiles/{publicKey}", "spec has no 500 response for this route"],
  ["PUT /api/profiles/{publicKey}/encryption-key", "spec has no 400 response for this route"],
]);

module.exports = KNOWN_SPEC_GAPS;
